language: node_js
node_js:
  - '8.9.0'
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - npm install && npm run test
after_script:
  - npm run coverage
