import express from 'express';
import expressValidator from 'express-validator';
import bodyParser from 'body-parser';
import path from 'path';
import dotenv from 'dotenv';
import swaggerUi from 'swagger-ui-express';
import carsRoute from '../api/routes/cars';
import usersRoute from '../api/routes/users';
import ordersRoute from '../api/routes/orders';
import apiError from '../middlewares/apiError';
import swaggerDocument from '../swagger/swagger.json';
dotenv.config();

const { notFoundError, serverError } = apiError;
const app = express();
const port = process.env.PORT || 3000;
app.use(bodyParser.urlencoded({ extended: false }));
app.use(expressValidator());
app.use('/static', express.static(path.join(__dirname, 'ui')));
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));
app.use('/api/v1/auth', usersRoute);
app.use('/api/v1/car', carsRoute);
app.use('/api/v1/order', ordersRoute);
app.use(notFoundError, serverError);
app.listen(port, () => console.log(`Should Be Listening On Port ${port}...`));
export default app;
