const cars = [{
    id : 1,
    owner : 1,
    createdOn : new Date(),
    state : 'new',
    status : 'available',
    price : 160000.00,
    manufacturer : 'BMW',
    model : '2-0-1-9',
    bodyType : 'car'
},
{
    id : 2,
    owner : 1,
    createdOn : new Date(),
    state : 'used',
    status : 'available',
    price : 1600000.00,
    manufacturer : 'TOYOTA',
    model : '1-9-9-9',
    bodyType : 'car'
},
{
    id : 3,
    owner : 2,
    createdOn : new Date(),
    state : 'new',
    status : 'available',
    price : 45000000.00,
    manufacturer : 'BENZ',
    model : '2-0-1-9',
    bodyType : 'truck'
},
{
    id : 4,
    owner : 1,
    createdOn : new Date(),
    state : 'new',
    status : 'available',
    price : 1600000.00,
    manufacturer : 'HONDA',
    model : '2-0-1-9',
    bodyType : 'car'
},
{
    id : 5,
    owner : 1,
    createdOn : new Date(),
    state : 'used',
    status : 'available',
    price : 250000.00,
    manufacturer : 'BMW',
    model : '1-9-9-8',
    bodyType : 'car'
},
{
    id : 6,
    owner : 3,
    createdOn : new Date(),
    state : 'used',
    status : 'available',
    price : 475000000.00,
    manufacturer : 'BMW',
    model : '2-0-1-9',
    bodyType : 'trailer'
},
{
    id : 7,
    owner : 1,
    createdOn : new Date(),
    state : 'new',
    status : 'available',
    price : 160000000.00,
    manufacturer : 'BMW',
    model : '2-0-1-9',
    bodyType : 'van'
},
{
    id : 8,
    owner : 2,
    createdOn : new Date(),
    state : 'used',
    status : 'available',
    price : 1600000.00,
    manufacturer : 'VOLKS WAGEN',
    model : '2-0-1-6',
    bodyType : 'car'
},
{
    id : 9,
    owner : 2,
    createdOn : new Date(),
    state : 'new',
    status : 'available',
    price : 990000.00,
    manufacturer : 'KIA',
    model : '2-0-1-9',
    bodyType : 'car'
},
{
    id : 10,
    owner : 1,
    createdOn : new Date(),
    state : 'new',
    status : 'sold',
    price : 1600000.00,
    manufacturer : 'BENZ',
    model : '2-0-1-9',
    bodyType : 'car'
},
{
    id : 11,
    owner : 1,
    createdOn : new Date(),
    state : 'new',
    status : 'sold',
    price : 61600000.00,
    manufacturer : 'VOLKS WAGEN',
    model : '2-0-1-9',
    bodyType : 'car'
},
{
    id : 12,
    owner : 1,
    createdOn : new Date(),
    state : 'new',
    status : 'sold',
    price : 160300000.00,
    manufacturer : 'TOYOTA',
    model : '2-0-1-9',
    bodyType : 'car'
},
{
    id : 13,
    owner : 1,
    createdOn : new Date(),
    state : 'used',
    status : 'sold',
    price : 87600000.00,
    manufacturer : 'BENZ',
    model : '2-0-1-1',
    bodyType : 'car'
},
{
    id : 14,
    owner : 1,
    createdOn : new Date(),
    state : 'new',
    status : 'sold',
    price : 99600000.00,
    manufacturer : 'BMW',
    model : '2-0-1-9',
    bodyType : 'car'
},
{
    id : 15,
    owner : 1,
    createdOn : new Date(),
    state : 'used',
    status : 'sold',
    price : 1600000.00,
    manufacturer : 'BENZ',
    model : '2-0-1-9',
    bodyType : 'car'
}];
export default cars;